name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
#     - uses: actions/checkout@v2
    - name: Install gtest
      run: ls && sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade && sudo apt-get install -y build-essential && sudo rm /var/lib/dpkg/lock-frontend && sudo dpkg --configure -a && sudo apt-get install -y tzdata && sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo apt-get install -y cmake && sudo apt-get install -y cmake protobuf-compiler && sudo apt-get install -y make 
    - name: Building googgletest
      run: ls && cd googleTest_testing && ls && cmake CMakeLists.txt && make && ls
    - name: Test
      run: ls && cd googleTest_testing && ls && ./executeTests
    - name: building Catch2
      run: ls && cd Catch2_testing && ls sudo cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install 
#       && cd examples && ls && g++ 020-TestCase-1.cpp && ls && ./a.out
    - name: ls && cd examples && ls && g++ 020-TestCase-1.cpp && ls && ./a.out
